# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161018_2034'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='click',
            unique_together=set([]),
        ),
    ]
