# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161019_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
